### ISSUE TITLE
ABM Fails need to Fail

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#10]
The ABM is currently failing in non-critical ways.  This makes it unclear if the model has actually run or not.  In many cases many logs and outputs have populated, so someone new can easily mistake a failed run as a successful run that just ran really quickly.  The ABM setup needs to be updated so that a crticial fail means are hard stop in the model sequence - ideally with a nice clear notice to the user that something went wrong. 

Currently in the setup, there is a critical fail in the ABM, and the setup continues through 3 iterations of skimming in Visum and failed ABM runs...

**Comment by bstabler** [comment]
we agreed to remove the ct-ramp outputs and then check for a key output such as indiv_trips.csv.
