### ISSUE TITLE
Cleaning and Sorting ABM outputs

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#11]
I was just looking over the output folder with Sam.
In that process we were noticing the current mess of files that the ABM “Build” configuration is producing.  A number of notes about those output files.

1.	I don’t think we are going to want to explain all those output files in the user guide.  I think we will want to prune it down to only final iteration files.
2.	Sam suggests “binning” the output into subdirectories (like CVM as an example).  I think that idea could help make the output space more manageable.
3.	If you are going to consider Sam’s suggestions – you will likely want to think about that before doing too much work with the data processing scripts.

**Comment by bstabler** [comment]
Also make sure to empty the outputs folder at the start of a model run

**Comment by bstabler** [comment]
we agreed to
  - add networks, skims, trips, other
  - add optionally delete the earlier iterations ctramp output files

**Comment by bstabler** [comment]
I think "optionally delete the earlier iterations ctramp output files" is no longer needed now that there are networks, skims, trips, and other subfolders.

**Comment by bettinardi** [comment]
Disagree 
iteration information is create for model building and calibration, but once the model is calibrated and operational there will be very few times, if any, that we need to go back and use anything but the final iteration.  We can't drag around ~8 GBs of extra data files every application of the model.  We need a quick and simple delete feature.  Since the run environment knows the final iteration number / files, the run environment is the best time to clean up unwanted files.  Please add a delete, so that only the final set of output files remains.

**Comment by bstabler** [comment]
will do

**Comment by bstabler** [comment]
I'm going to close this and create a new issue for optionally delete the earlier iterations ctramp output files since I want to create something more general related to cleaning up after a run.
