### ISSUE TITLE
post-process synpop person table to add a university students field

### ISSUE THREAD

**Issue by bstabler** [RSGInc/SOABM#12]
Part 1 - @DDudich 

#Scripts Adds Major university column to persons file as well as fixing Null value in Standard Occupation Classification (SOC) column.

x <- read.csv("persons.csv",as.is=T)
x$soc <- as.numeric(gsub("NUL",0,x$soc))
x$majoruni <-0
x<- x[order(x[,30],x[,10]),c(1:23,31,24:30)]
 x$PERID <- 1:nrow(x)
write.csv(x,"persons_sorted_uni.csv",row.names=F)

**Comment by bettinardi** [comment]
We also have to update the MAZ numbers in the household table to MAZseq numbers.  This process should be in the ABM, not the pop syn:

   rownames(maz) <- maz$NO
   hh$maz <- maz[as.character(hh$maz),"MAZ"]
   write.csv(hh,"households.csv",row.names=F)

**Comment by bstabler** [comment]
Part 1 will go into popsim pre/post-processors

Part 2 is already done, see [zoneChecker](https://github.com/RSGInc/SOABM/blob/master/template/scripts/zoneChecker.py)

**Comment by bstabler** [comment]
Part 1 is now https://github.com/RSGInc/populationsim/issues/16.
