### ISSUE TITLE
Pull Fare District amounts into an input file

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#13]
Currently transit fare districts are hard coded.  Fare districts need to be established at the TAP level and then fares by district coded in some input file location (not in a script).  The user guide will need to be updated accordingly.

**Comment by bstabler** [comment]
We agreed to code TAPs (StopAreas) with a FareDistrict code such as "GP" and "RV" and read a CSV file of fares by TAP pair.

**Comment by bstabler** [comment]
See https://github.com/RSGInc/SOABMTest/commit/844e2109c036f387f5cf625553eb4412616abc49
