### ISSUE TITLE
Remove FACTYPE and cleanup some other network attributes

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#19]
As soon as possible, the link field - FACTYPE needs to be removed from the version file and user guide.  ODOT maintains the Visum defined attribute "PLANNO" for FC, not the UDA "FACTYPE".  FACTYPE needs to be cleared from the version file and user guide to prevent future confusion.  In general, the link and zone attributes need to be brought down to only the fields used by the model (or defined in the user guide - like PLANNO), to minimize error.

**Comment by bstabler** [comment]
We need to update the connector generation process in the SOABM.py script as well since it uses FACTYPE

**Comment by bettinardi** [comment]
We should also plan to remove the sidewalk and bikefac fields as well, since they are redundant.  I believe the Truck fields need to go too.  We should also consider a different design for the toll fields.  I suggest a toll type (1, 2, 3, 4 or a, b, c, d), coded, and then there is a look up file (csv) where each toll type is defined for how that toll type applies to the different user / vehicle classes.

**Comment by bettinardi** [comment]
see link table in #27

**Comment by bstabler** [comment]
still need to make the changes in #27
