### ISSUE TITLE
Building Pop Syn zonal totals from Pop Syn tables

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#21]
It's overly burdensome to have the analysts ensure that the pop syn and zone inputs in the ABM are consistent.

The setup should be - 
The input version file holds the pop syn controls (inputs) at the TAZ/MAZ level, but if they are not consistent it's not a problem.
The code takes the input household and person table and builds the TAZ and MAZ zone tabulations from those data-sets and then updates the appropriate fields in the working (output) version files - and uses those fields for the ABM (if they are used at all).

This will greatly simplify setting up new scenarios with different syn pops.

**Comment by bstabler** [comment]
see #27
