### ISSUE TITLE
Adding 24 hour volume to PM version file

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#22]
From my email:

I see that the “report_count_volumes” function that now runs at the end of the ABM complies the 5 periods into a daily.

This leads me to two requests:

1.	The PM will be our typical analysis period.  Therefore, it will be the version file we go to 9 times out of 10.  Please update the “report_count_volumes” function to:
a.	Produce two lists.  One for volumes at count locations and one for daily volumes everywhere (all links).  We will need volumes on all links to compare across scenarios, not just count locations.
b.	End the for loop on pm and load the 24 hour modeled volume for all links into the PM version file.  That way we can see both the PM peak and daily result in the one version file.
c.	Update the function to save out volumes by period as well, so that we can do count validation by period as desired.  We might not care about all the periods, but we will definitely care about PM peak in calibration, not just daily.
2.	As 1.c suggests, please add to the html count (volume for scenario comparison) validation by time period, so this will be a very important calibration measure.

**Comment by bstabler** [comment]
add after #23 is merged

**Comment by binnympaul** [comment]
This has been completed.
