### ISSUE TITLE
move user's guide to wiki

### ISSUE THREAD

**Issue by bstabler** [RSGInc/SOABM#25]
We need to move the [user's guide](https://github.com/RSGInc/SOABM/blob/master/SOABM_UserGuide.docx) to the wiki, link swim.  @bettinardi - when we do, we need to change the order of the sections.  Section 6 (Creating and Running a Scenario) should be closer to the start – if not the first thing.

**Comment by bettinardi** [comment]
Sure - I think a lot of the flow / structure will be improved once we get this in a wiki.

**Comment by bstabler** [comment]
@bettinardi - we'll also need to update a few other sections:
  - STEP 2 – CREATE SKIMS USING TOMTOM SPEEDS will need to be removed and STEP 8 – CREATE SKIMS AND ASSIGNMENTS USING CONGESTED SPEEDS will no longer need to say "CONGESTED SPEEDS"
  - VDFs will need to updated based on the SANDAG link,node functions, as well as node and link attribute tables, including the work DKS is doing on coding the network
  - Remove section related to Figure 8 links by TomTom speed data
  - Add documentation page for CVM and SWIM externals 
  - Move OR-RAMP PROPERTIES FILE table to an appendix/separate page
  - Show the entire list of columns and the entire list of demand matrices, no matter how long they might be

**Comment by bstabler** [comment]
also add notes on how to convert md to docx like [BKRCast](https://github.com/RSGInc/SOABM/blob/master/template/scripts/zoneChecker.py)

**Comment by bstabler** [comment]
See the [wiki](https://github.com/RSGInc/SOABM/wiki)

**Comment by bstabler** [comment]
I also need to update the https://github.com/RSGInc/SOABM/wiki/transit-network-coding page.

**Comment by bstabler** [comment]
I added more info for the custom [VDF](building-the-odot-vdf) and added new pages (and links to) for [CVM](CVM) and [external model](external-model).  I think that's good for now.
