### ISSUE TITLE
User shouldn’t code the MAZ (mainzone) SEQMAZ attribute

### ISSUE THREAD

**Issue by bstabler** [RSGInc/SOABM#27]
the code should do it internally and write it out

**Comment by bstabler** [comment]
we're going to:
  - remove this field from VISUM and have a script calculate it and populate the field in the output version file 
  - move the zoneChecker.py to the beginning and rename it so that it does the following - change the hh home zone to seqmaz, update seqmaz in the version file, summarize popsyn data at the TAZ,MAZ level that is required for CT-RAMP inputs (such as total HHs)

**Comment by bettinardi** [comment]
Here's what we're going to do:

## Links

Field | Purpose | User Edits | Notes
-- | -- | -- | --
NO | Internal | N |  
FROMNODENO | Internal | Y |  
TONODENO | Internal | Y |  
TYPENO | vdf look-up | Y | User guide needs to explain available vdfs
TSYSSET | Modes available | Y |  
LENGTH | length | Y |  
NUMLANES | number of lanes | Y |  
CAPPRT | interally overwritten | N |  
V0PRT | posted speed | Y |  
AM_SPEED | tod_speed | N | except for the calibration network
PLANNO | FC | Y |  
AREATYPE | remove |   | unless we want to keep it for the look-up
BIKEFAC | remove | N | not currently populated correctly or used by code
EA_SPEED | tod_speed | N | except for the calibration network
EV_SPEED | tod_speed | N | except for the calibration network
FACTYPE | remove |   | used to be the FC, now PLANNO
HOV_PRIORITY | remove |   | not sure where this is from
LANECAP | capacity per lane per hour | Y |  
LANES_AM | internally calculated | N |  
LANES_EA | internally calculated | N |  
LANES_EV | internally calculated | N |  
LANES_MD | internally calculated | N |  
LANES_PM | internally calculated | N |  
MD_SPEED | tod_speed | N | except for the calibration network
OBS_SPEED_YR | remove |   | creaded for documentation originally, no longer needed
OCC_AM | remove |   | from TomTom delete
OCC_EA | remove |   | from TomTom delete
OCC_EV | remove |   | from TomTom delete
OCC_MD | remove |   | from TomTom delete
OCC_PM | remove |   | from TomTom delete
PM_SPEED | tod_speed | N | except for the calibration network
SIDEWALK | remove | N | not currently populated correctly or used by code
SPEED | remove |   | Update procedure files to use v0prt
SPEEDCAT | remove |   | from TomTom delete
SPEEDFRIDAY |   |   | TomTom historic speed, alex will consider deleting
SPEEDMONDAY |   |   | TomTom historic speed, alex will consider deleting
SPEEDSATURDAY |   |   | TomTom historic speed, alex will consider deleting
SPEEDSUNDAY |   |   | TomTom historic speed, alex will consider deleting
SPEEDTHURSDAY |   |   | TomTom historic speed, alex will consider deleting
SPEEDWEDNESDAY |   |   | TomTom historic speed, alex will consider deleting
TOLL_DA_AM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_DA_EA | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_DA_EV | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_DA_MD | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_DA_PM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S2_AM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S2_EA | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S2_EV | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S2_MD | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S2_PM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S3_AM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S3_EA | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S3_EV | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S3_MD | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_S3_PM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_TRUCK_AM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_TRUCK_EA | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_TRUCK_EV | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_TRUCK_MD | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TOLL_TRUCK_PM | remove |   | the ABM will not have time of day tolling, just one constant   toll for the day
TRAN_PRIORITY | remove |   | probably old TomTom
TRUCK_AM | remove |   | not sure where this is from
TRUCK_EA | remove |   | not sure where this is from
TRUCK_EV | remove |   | not sure where this is from
TRUCK_MD | remove |   | not sure where this is from
TRUCK_PM | remove |   | not sure where this is from

## MAZ

Field | Purpose | Notes
-- | -- | --
NO | MAZ number | keep see user guide
COUNTY | County | read by CT-RAMP
DISTNAME | Districts | read by CT-RAMP
DPARKCOST |   | keep see user guide
DSTALLSOTH |   | keep see user guide
DSTALLSSAM |   | keep see user guide
DUPLEX_HH | remove |  
ECH_DIST |   | keep see user guide
EMP_ACCFD |   | keep see user guide
EMP_ADMIN |   | keep see user guide
EMP_AGR |   | keep see user guide
EMP_ARTS |   | keep see user guide
EMP_CONSTR |   | keep see user guide
EMP_EDUC |   | keep see user guide
EMP_FINANC |   | keep see user guide
EMP_FOOD |   | keep see user guide
EMP_HEALTH |   | keep see user guide
EMP_INFO |   | keep see user guide
EMP_METAL |   | keep see user guide
EMP_MGMT |   | keep see user guide
EMP_MIN |   | keep see user guide
EMP_OTHER |   | keep see user guide
EMP_POSTAL |   | keep see user guide
EMP_PROF |   | keep see user guide
EMP_PUBADM |   | keep see user guide
EMP_REALES |   | keep see user guide
EMP_RETAIL |   | keep see user guide
EMP_SPORT |   | keep see user guide
EMP_TOTAL |   | keep see user guide
EMP_TRANS |   | keep see user guide
EMP_UTIL |   | keep see user guide
EMP_WHOLE |   | keep see user guide
EMP_WOOD |   | keep see user guide
ENROLL9_12 |   | keep see user guide
ENROLLADSC |   | keep see user guide
ENROLLCOLL |   | keep see user guide
ENROLLCOOT |   | keep see user guide
ENROLLK_8 |   | keep see user guide
HCH_DIST |   | keep see user guide
HH |   | Calculate based on SynPop
HHP |   | Calculate based on SynPop
HHS | remove |  
HH_1 | remove |  
HH_2 | remove |  
HH_3 | remove |  
HH_4 | remove |  
HH_GQ_CIV | remove |  
HH_GQ_MIL | remove |  
HH_GQ_UNIV | remove |  
HOTELRMTOT |   | keep see user guide
HPARKCOST |   | keep see user guide
HSTALLSOTH |   | keep see user guide
HSTALLSSAM |   | keep see user guide
MF_HH | remove |  
MH_HH | remove |  
MPARKCOST |   | keep see user guide
MSTALLSOTH |   | keep see user guide
MSTALLSSAM |   | keep see user guide
NUMFREEHRS |   | keep see user guide
PARKACRES | park acres currently | might need to revise in the future
PARKAREA |   | keep see user guide
POP |   | Calculate based on SynPop
SCHDIST |   | keep see user guide
SCHDIST_NA |   | keep see user guide
SEQMAZ |   | keep but change to internal calculated
SF_HH | remove |  
SP_ID | remove | junk
SP_ID_1 | remove | junk
TAZ |   | keep see user guide
TAZID | remove |  
TERMTIME |   | keep see user guide
UNIVERSITYSQFTCLASS |   | keep see user guide
UNIVERSITYSQFTOFFICE |   | keep see user guide
UNIVERSITYSQFTREC |   | keep see user guide
WRK_EXT_PR |   | keep see user guide
AREAMI2 | internal | all zones need a polygon

## TAZ

Field | Purpose | Notes
-- | -- | --
NO |   | keep
COUNTY |   | remove all others

**Comment by bstabler** [comment]
Also add LINK AUX_LANES field and set to zero for now
