### ISSUE TITLE
PCE to Vehicle Factoring

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#41]
As ODOT implements PCE assignment in the ABM, the team needs to remember that final link volume attributes need to be saved back to the network as User Defined Attributes (UDA) that have been adjusted for the truck PCE factor.  Each period will need an auto, truck, and total volume.  In addition to a daily set of totals that will be summed up at the end of each period run and added to the PM file (similar to SWIM's operation).  

As this is completed it is important that we remember to update the scripts that pull volume for the visualizer, as they will need to point to these new Volume counts as opposed to the PCE assignment. 

Currently 3 different PCEs (for different truck classes are being discussed).  If that ends up being the approach, then ABM will likely only have one truck PCE matrix.  Therefore the code will have to calculate and report out (to a text file) the weighted average PCE factor for each collaposed truck matrix by period.  The code will then be repsonsible for applying the correct weighted PCE factor to the truck PCE demand for each period, so that each period correctly converts the collapsed truck demand back to vehicles which get saved as the UDA (truck volume for each period).

**Comment by bettinardi** [comment]
@bstabler and @binnympaul 
Did we take care of this - are the truck volumes that are pulled out PCEs or trucks?

**Comment by bstabler** [comment]
In VISUM, this is under Network + TSys/Modes/DSegs + select Truck + Edit + and PCU (passenger car units).  It looks like it is currently set as 1.
