### ISSUE TITLE
taz 343 assignment demand too high

### ISSUE THREAD

**Issue by bstabler** [RSGInc/SOABM#42]
Binny highlighted that we have extreme congestion around TAZ 343 (with one MAZ 34301, SEQMAZ – 431).   ODOT has been investigated and agree that there are network issues.

However, there also appears to be something grossly incorrect with the demand.  The MAZ that represents that TAZ has a total employment of 76 and has 52 households.  In the AM (1.5 hour, 7-8:30) assignment period, that single MAZ has a total demand of ~2000 trips – way too high of an AM peak demand for that land use (it has about 4,000 in the PM 2 hour peak).

**Comment by bstabler** [comment]
the buildTripMatrices maz to taz lookup was off by one.  Thus, all that demand in taz 343 should have gone to taz 342, which has 1249 employees.  I'm testing the fix now.

**Comment by bstabler** [comment]
this was not correctly fix.  It worked for taz 100, 343, etc., but these tazs only have one maz.  It doesn't work for multiple mazs per taz.  @binnympaul to fix.

**Comment by binnympaul** [comment]
The buildTripMatrices function was updated to use the correct zone indexing. The model was re-run and outputs were verified for TAZ 100, 343 and 113. The fix works for both single MAZ and multiple MAZ cases.
