### ISSUE TITLE
Cleaner ABM end state

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#50]
If I'm looking at the ABM correctly, the end files that a user of the ABM will most typically go to after a run are outputs/networks/taz_skim_period_speed.ver

This file naming means something to modeling steps / process, but the file name means nothing to the end user and is not intuitive at all.

I would like to suggest that the file name get changed to something like - "FinalHighwayAssignment_Period.ver".

For the Transit files, "tap_skim_period_setX.ver".  It would be helpful to change the file naming to "FinalTransitAssignment_Period_SetX.ver".  Maybe since all these files would start with "Final" we could drop the final.  But basically we need a file name that makes a little more sense than the current.  Skims in the file name does not represent why the user would go to that file, it just represents what the model flow uses the file for - skimming.  But we need to make the model name meaningful to the user, not the coder.

**Comment by bettinardi** [comment]
What file do the final daily traffic counts get placed.  We might need to expand this to have a final Highway assignment version file that has the auto, truck, and total assignments by all five periods and daily.  Can the summary transit file (#52 ) and the summary highway file be combined into a final results file - one-stop shop?

If it works out, I think it would be great if the outputs folder included a csv copy of the transit and highway results (separate files) with all of the period information from the different version files that we want to copy into a single version file.  Having csv copies would allow for better functionality and scenario comparison later on - like a database (dataset) external to Visum, so we can script processes to plot or summarize different elements of the results across years and scenarios without having to open Visum.  So it would ideal, if the update from this issue and issue #52 included a csv copy of the data as well as a single version file copy.

**Comment by binnympaul** [comment]
File naming has been updated. A final summary version file is also produced. CSV copy of data is also produced
