### ISSUE TITLE
Transit version files

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#52]
Currently 15 tap version files are created, each with their own transit assignment by set 1-3 and time of day and their own results. Two issues:
 - It creates a lot of files that are hard to interpret and take up a lot of space
 - The user needs a transit file (or an everything file, highway and transit) where all the results across all sets and all periods are totaled up and put into a signal file where the user can see all the results in one file without having to open up 15 transit files to see what the results look like over the day.

This is related to cleaning up the end state and file naming in #50

**Comment by binnympaul** [comment]
File naming has been updated. A final summary version file is also produced.
