### ISSUE TITLE
PopSim Automated consistencies with ABM

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#53]
Right now, if the user updates the Syn Pop, my understanding is that the user needs to:

1) have a completed ABM with the old Syn Pop, or start a new ABM run and let it fail with the new Syn Pop.
2) use the MAZ field out of the ABM, which is a MAZ seq, to update the Pop Sim output to have a MAZ seq number instead of a true MAZ identifying number.  While a MAZ seq can be assumed for the Syn Pop, the only save way is to use the seq number out of a previous ABM run.
3) The user then needs to re tabulate a series of MAZ and TAZ measures from the Syn Pop to the MAZ and TAZ tables for use in the ABM - to ensure they are consistent.
4) The user has updated MAZ and TAZ fields from the Syn Pop Summaries that then need to be loaded back into the ABM tables (in Visum).  The user can then take their updated household table (with MAZ seq numbering) and their updated MAZ and TAZ summaries and run the ABM with consistent and linked inputs.

When the ABM is running it needs to do the 4 steps above so that the user can just provide a new syn pop and the code ensures that the MAZ numbers are sequenced correctly and all the important MAZ and TAZ tabulations are updated to align with the Syn Pop that has been input.

**Comment by bettinardi** [comment]
This issue should include #43

**Comment by bettinardi** [comment]
Additionally, this processing should include basic quality checks in alignment with syn pop requirements layout in issue #54.  The model should have a hard stop if any  syn pop fields required for the ABM are missing, or have values that are outside of define bounds - like NAs.  NA cleaning should be built into the process - changing NULL values or NA to values within bounds.

**Comment by bettinardi** [comment]
Noting that if we create a visitor population we will need to create a new "VISITOR_HH" MAZ field to help build all the inputs.  Visitor households would need to get removed from the total population to calculate items like population, HH, and HHP...

**Comment by binnympaul** [comment]
Which TAZ & MAZ measures need to be computed from the synthetic population?

**Comment by binnympaul** [comment]
"use the MAZ field out of the ABM, which is a MAZ seq, to update the Pop Sim output to have a MAZ seq number instead of a true MAZ identifying number. While a MAZ seq can be assumed for the Syn Pop, the only save way is to use the seq number out of a previous ABM run." Is not this already handled by the existing zone checker script? I believe it copies the Seq MAZ to the HH file from the MAZ data.
