### ISSUE TITLE
Syn Pop Context for the User Guide

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#54]
As we are updating the Syn Pop for the ABM, we are finding all kinds of questions about how the ABM is using the Syn Pop information and how to build the new syn pop correctly.

The user guide needs to spell out each field that it reads from the syn pop household and person tables and what each field needs to be.

Examples:
MAZ needs to be a sequenced number (although there should be a note in the user guide that the code does this sequencing automatically, assuming #53 is addressed).
Sex - what does the code assume 1 is versus 2.  Is there an option for none provided, or are the values of 1 and 2 strictly required.
Building type - what does the ABM code assume each building code stands for, same for occupation, work status....  all of them.  

Each field needs to be spelled out in the user guide, so that a new analyst can properly sink up the PUMS record output with the codes / fields that the ABM requires.  While it may seem straight forward now, the PUMS can always change, so there needs to be a clear record for what was assumed for each code /field.

**Comment by jfdman** [comment]
Added household and person table descriptions
