### ISSUE TITLE
User Guide Dollar Units

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#60]
The user guide needs to specify the year that the dollars need to be in for any dollar input (income, tolls...).  The tolls state 2010:
https://github.com/RSGInc/SOABM/wiki/Networks-and-Zone-Data#link-attributes

But the income tabulations are not specified:
https://github.com/RSGInc/SOABM/wiki/Running-the-Population-Synthesizer

A question was just raised as to what year the model estimation represents, and that shouldn't the income brackets represent the estimation data year.

**Comment by jfdman** [comment]
The income tabulations state $2010.
