### ISSUE TITLE
Visualizer can't assume identical networks

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#65]
The visualizer is intended to compare different scenarios.  It is common that scenarios will have changes to the network.  Currently the visualizer code assumes each scenario has identical links.

The solution is for the visualizer to build a sub-set of identical link identifiers between the two scenarios and to not include non-identical links in the link-to-link volume comparison.  The full network volumes can still be compared in any VMT or VHT (network-wide) comparisons.

**Comment by binnympaul** [comment]
adding this to contingency scope

**Comment by binnympaul** [comment]
addressed under contingency work
