### ISSUE TITLE
Visualizer needs a user guide

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#66]
Currently the visualizer has no user guide.
Some basic pages need to be drafted to describe how to operate the visualizer via the batch file.

**Comment by binnympaul** [comment]
adding this to contingency scope

**Comment by bettinardi** [comment]
I disagree.
The basics of how to operate the vis tool should go into the user guide under the current contract.  Perhaps more advanced topics around operating the user guide could be contingency.

**Comment by bettinardi** [comment]
Example - section 2.3 of the model calibration document is already written and covers many of the aspects that belong in the user guide on operating the batch file and the visualizer.  Helping to show that this is not a contingency request.  It's about completing the user guide with content and instructions that have already been written or need to get written for the tasks completed under existing / scoped work efforts.
