### ISSUE TITLE
Visualizer Added Overview Check

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#70]
In reading the user guide it jumped out at me that the balance between employment and workers is important for the analyst to watch.  

Would it be an easy lift to add an indicator to the overview page on total workers and employment.  On the left I'm thinking under total households and population would be a total works and then total employment.  And on the right would be an extra dial for a ratio comparison.  If we can add that, I think the right could also use a quick average household size dial as well (to help keep a balance).

**Comment by binnympaul** [comment]
total employment and jobs per worker comparisons added under contingency work
