### ISSUE TITLE
Update to Transit Everywhere TMIP-EMAT switch

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#95]
Alex noted to RSG that Transit everywhere has an issue in that all of the demand that shifts to Transit everywhere is not assigned.  Binny had some low cost ideas on how some level of this demand might be represented in the OD matrices...

To be discussed/planned further.

**Comment by binnympaul** [comment]
A very simplistic approach would be to assign the transit demand as autos assuming an occupancy level. Some percentage of transit everywhere demand will be met by some sort of fixed-guide-way transit service. The percentage of transit as autos and occupancy level could be an user input.

Realistically, the transit everywhere service operator would be routing these vehicles in an optimal fashion to reduce operating cost.  Implementing a solution which simulates optimal routing may not be a low-cost solution.
